from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.base import generate_uuid


class UsageRecord(Base):
    """
    Persisted record of a single usage event generated by a user.

    Each instance captures when a particular action occurred and, optionally,
    which workflow and workflow run it relates to. This model is intended for
    analytics, usage tracking, and audit-style reporting.

    Attributes
    ----------
    id:
        Stable UUID primary key for this usage record.
    user_id:
        Identifier of the user who triggered the event.
    event_type:
        Short string that categorizes the kind of event that occurred
        (for example: "login", "workflow_run_started",
        "workflow_run_completed", "workflow_created"). The allowed values
        are defined by the usage tracking logic elsewhere in the application.
    workflow_id:
        Optional identifier of the workflow associated with the event.
    run_id:
        Optional identifier of a workflow run associated with the event.
    recorded_at:
        Timestamp (in UTC) when the event was recorded in the system.
    """

    """
    Represents a single usage event generated by a user.

    Each record captures when a specific action occurred and, when applicable,
    which workflow and run it was associated with. These records can be used
    for analytics, auditing, and billing-related reporting.

    workflow_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("workflows.id", ondelete="SET NULL"), nullable=True
    )
    run_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("workflow_runs.id", ondelete="SET NULL"), nullable=True
    )

    - ``"workflow_execution"``: execution of a stored workflow, optionally linked
      to ``workflow_id`` and a concrete ``run_id``.
    - ``"api_call"``: a direct API request made by or on behalf of the user.

    Additional event types may be introduced over time; callers should use
    consistent, documented string values when creating new records.
    """

    __tablename__ = "usage_records"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    event_type: Mapped[str] = mapped_column(String(50))
    workflow_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("workflows.id", ondelete="SET NULL"), nullable=True
    )
    run_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("workflow_runs.id", ondelete="SET NULL"), nullable=True
    )
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
