"""add encrypted_openai_key to users

Revision ID: 020c681594a6
Revises: e75939a47db1
Create Date: 2026-03-13 16:21:13.486671

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020c681594a6"
down_revision: Union[str, Sequence[str], None] = "e75939a47db1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "usage_records", "workflows", ["workflow_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "usage_records", "workflow_runs", ["run_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "users", sa.Column("encrypted_openai_key", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "encrypted_openai_key")
    # ### end Alembic commands ###
